# Generated by Django 3.2.5 on 2021-07-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('text', models.TextField(verbose_name='Text')),
                ('importance', models.CharField(blank=True, choices=[('v', 'Very important'), ('i', 'Important'), ('n', 'Not important')], default='n', help_text='Importance', max_length=1)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
